version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run: python -V
      - run: sudo apt-get install python-setuptools
#      - run: sudo python setup.py install
  MigrateChange:
    executor: python/default
    steps:
      - run: python -V
    
workflows:
  main:
    jobs:
      - build-and-test
